package com.restaurant_pos.backend.order;
import com.restaurant_pos.backend.menu.*; import com.restaurant_pos.backend.orderitem.OrderItem; import com.restaurant_pos.backend.table.*; import jakarta.transaction.Transactional; import org.springframework.stereotype.Service; import java.math.*; import java.util.*;
@Service public class OrderService {
 private final OrderRepository orders; private final RestaurantTableRepository tables; private final MenuRepository menus;
 public OrderService(OrderRepository o,RestaurantTableRepository t,MenuRepository m){orders=o;tables=t;menus=m;}
 public List<Order> all(){return orders.findAll();} public Order get(Long id){return orders.findById(id).orElseThrow(()->new IllegalArgumentException("Order not found."));}
 @Transactional public Order create(Long tableId){RestaurantTable t=table(tableId);if(t.getStatus()!=TableStatus.AVAILABLE)throw new IllegalStateException("Table is occupied.");Order o=new Order();o.setTableId(tableId);t.setStatus(TableStatus.OCCUPIED);tables.save(t);return orders.save(o);}
 @Transactional public Order addItem(Long id,Long menuId,int quantity){if(quantity<=0)throw new IllegalArgumentException("Quantity must be positive.");Order o=open(id);Menu m=menus.findById(menuId).orElseThrow(()->new IllegalArgumentException("Menu item not found."));OrderItem i=o.getItems().stream().filter(x->x.getMenuId().equals(menuId)).findFirst().orElseGet(()->{OrderItem x=new OrderItem();x.setOrder(o);x.setMenuId(menuId);x.setUnitPrice(m.getPrice());o.getItems().add(x);return x;});i.setQuantity((i.getQuantity()==null?0:i.getQuantity())+quantity);recalc(o);return orders.save(o);}
 @Transactional public Order updateItem(Long id,Long itemId,int quantity){Order o=open(id);OrderItem i=item(o,itemId);if(quantity<=0)o.getItems().remove(i);else i.setQuantity(quantity);recalc(o);return orders.save(o);}
 @Transactional public Order removeItem(Long id,Long itemId){Order o=open(id);o.getItems().remove(item(o,itemId));recalc(o);return orders.save(o);}
 @Transactional public Order transfer(Long id,Long targetId){Order o=open(id);if(o.getTableId().equals(targetId))throw new IllegalStateException("Choose a different table.");RestaurantTable from=table(o.getTableId()),to=table(targetId);if(to.getStatus()!=TableStatus.AVAILABLE)throw new IllegalStateException("Destination table is occupied.");from.setStatus(TableStatus.AVAILABLE);to.setStatus(TableStatus.OCCUPIED);o.setTableId(targetId);tables.save(from);tables.save(to);return orders.save(o);}
 @Transactional public Order checkout(Long id,PaymentMethod method,BigDecimal amountPaid){Order o=open(id);if(method==null)throw new IllegalArgumentException("Payment method is required.");if(o.getItems().isEmpty())throw new IllegalStateException("Cannot checkout an empty order.");if(amountPaid==null||amountPaid.compareTo(o.getTotal())<0)throw new IllegalArgumentException("Amount paid is less than the order total.");RestaurantTable t=table(o.getTableId());o.setPaymentMethod(method);o.setAmountPaid(amountPaid);o.setChangeAmount(amountPaid.subtract(o.getTotal()));o.setStatus(OrderStatus.COMPLETED);t.setStatus(TableStatus.AVAILABLE);tables.save(t);return orders.save(o);}
 private Order open(Long id){Order o=get(id);if(o.getStatus()!=OrderStatus.OPEN)throw new IllegalStateException("Order is not open.");return o;} private RestaurantTable table(Long id){return tables.findById(id).orElseThrow(()->new IllegalArgumentException("Table not found."));} private OrderItem item(Order o,Long id){return o.getItems().stream().filter(i->i.getId().equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException("Order item not found."));} private void recalc(Order o){o.getItems().forEach(i->i.setSubtotal(i.getUnitPrice().multiply(BigDecimal.valueOf(i.getQuantity()))));o.setTotal(o.getItems().stream().map(OrderItem::getSubtotal).reduce(BigDecimal.ZERO,BigDecimal::add));}
}
